[package]
name = "starfruit"
description = "A math library"
license = "MIT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"
paste = "1.0.14"

[features]
nightly = []
